#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Projet.Resource", IsApplication=true)]

namespace Projet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040005
			public const int country = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int desc = 2130968582;
			
			// aapt resource value: 0x7f04000e
			public const int historique = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int humidite = 2130968589;
			
			// aapt resource value: 0x7f040002
			public const int icon = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int lat = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int listFav = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int lon = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int rechercher = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int temp = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int tempMax = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int tempMin = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int ville = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int weatherImg = 2130968583;
			
			// aapt resource value: 0x7f04000c
			public const int windSpeed = 2130968588;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int item_historique = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int list_historique = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
